# Conexion a mysql local
spring.application.name=auramove
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Open-Meteo API (Clima, sin API key)
openmeteo.base-url=${OPENMETEO_BASE_URL}

# Spring Security - JWT
# IMPORTANTE: cambia este valor en produccion por uno aleatorio largo (min 32 caracteres)
#JwtUtil lee JWT_SECRET directamente desde la variable de entorno
springdoc.enable-hateoas=false